upgrade to v2.17.0 (#134)
* upgrade terraform-provider-consul to v2.17.0 at sha 07753a475393

* update resources; these seems to be from v2.16 but werent updated on master

* codegen, with error  on PeeringToken

* override PeeringToken field name for CSharp codegen to avoid csharp-specific enclosing types error

the relevant error was
```
pulumi-consul/sdk/dotnet/PeeringToken.cs(64,31):
error CS0542: 'PeeringToken': member names cannot be the same as their enclosing type
```

* codegen